INSERT INTO FORNECEDOR (ID, NAME, ACTIVE, CATEGORY, CONTACT) VALUES (1,'Maria', 'seila','chique', '123123');
INSERT INTO FORNECEDOR (ID, NAME, ACTIVE, CATEGORY, CONTACT) VALUES (2,'João', 'seila', 'chique', '123123');
